### ISSUE TITLE
Runtime Error while running the example in Windows

### ISSUE THREAD

**Issue by prashanth6693** [pygpc-polynomial-chaos/pygpc#2]
I am getting a runtime error when I run the plot_gpc_validation.py file in the example gallery . The error log is similar to the one shown in #3.  I am using Python 3.7.6 and numpy 1.19.0

**Comment by konstantinweise** [comment]
Do you use Windows, Linux or MacOS?

**Comment by konstantinweise** [comment]
The following also solves #3:
If you use Windows, there are differences regarding the multiprocessing. There, you have to encapsulate the example code in a main function:

```
def main():
    # ...
    # pygpc code
    # ...

if __name__ == '__main__':
    main()
```

Reason: On Windows subprocesses will import (i.e. execute) the main module at start. You need to insert an if __name__ == '__main__': guard in the main module to avoid creating subprocesses recursively.

In about 4 weeks we will release a new version of pygpc, where we will fix this issue!

Best,

Konstantin
